FROM nickistre/centos-lamp:latest

COPY src/ /var/www/html/

RUN /etc/init.d/mysqld start \
    && mysqladmin -uroot password 'c2FkZmFnZGZkc3Nm' \
    && mysql -e "CREATE DATABASE sqli_gbk DEFAULT CHARACTER SET utf8;" -uroot -pc2FkZmFnZGZkc3Nm \
    && mysql -e "use sqli_gbk;source /var/www/html/sqli_gbk.sql;" -uroot -pc2FkZmFnZGZkc3Nm \
    && rm /var/www/html/sqli_gbk.sql \
    && rm /var/www/html/phpinfo.php \
    && chmod -R 655 /var/www/html/ 
