version: '3'

services:

  mysql:
    image: mysql:5.6
    restart: always
    container_name: mysql_www
    environment:
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: skctf2o19
      MYSQL_DATABASE: skctf2019
    volumes:
      - ./skctf2019_admin.sql:/docker-entrypoint-initdb.d/skctf2019_admin.sql
  
  web:
    image: nimmis/apache-php5
    restart: always
    container_name: web_www
    links:
      - mysql
    depends_on:
      - mysql
    ports:
      - "8001:80"
    volumes:
      - ./www/:/var/www/html
      - ./flag.txt:/skctf2019/flag.txt
